export const SET_ENTITIES = 'SET_ENTITIES';
export const SHOW_SEARCH_BAR_PROGRESS = 'SHOW_SEARCH_BAR_PROGRESS';
export const SET_DATA_LOADED = 'SET_DATA_LOADED';
export const CHANGE_DEVELOPERS_STATUS = 'CHANGE_DEVELOPERS_STATUS';
export const CHANGE_COMMIT_SELECTED_STATUS = 'CHANGE_COMMIT_SELECTED_STATUS';
export const CHANGE_COMMITS_DEVELOPER = 'CHANGE_COMMITS_DEVELOPER';
export const ADD_PARENT = 'ADD_PARENT';
export const REMOVE_PARENT = 'REMOVE_PARENT';
export const SET_COMMIT_AS_REMOVED = 'SET_COMMIT_AS_REMOVED';

