export const SET_ENTITIES = 'SET_ENTITIES';
export const SHOW_SEARCH_BAR_PROGRESS = 'SHOW_SEARCH_BAR_PROGRESS';
export const SET_DATA_LOADED = 'SET_DATA_LOADED';
export const CHANGE_DEVELOPERS_STATUS = 'CHANGE_DEVELOPERS_STATUS';
